apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    annotations:
        kargo.akuity.io/authorized-stage: httpbin:uat
    labels:
        stage: uat
        tier: nonprod
    name: httpbin-uat-httpbin
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: httpbin
    source:
        path: ./
        repoURL: https://github.com/jeffmccune/kargo-demo.git
        targetRevision: project/httpbin/component/uat-httpbin
