apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  labels:
    argocd.argoproj.io/instance: httpbin-kargo-stages
  name: dev
  namespace: httpbin
spec:
  promotionTemplate:
    spec:
      steps:
      - config:
          checkout:
          - branch: main
            path: ./src
          - branch: project/httpbin/component/dev-httpbin
            create: true
            path: ./out
          repoURL: https://github.com/jeffmccune/kargo-demo.git
        uses: git-clone
      - config:
          path: ./out
        uses: git-clear
      - as: update-image
        config:
          images:
          - image: quay.io/holos/mccutchen/go-httpbin
          path: ./src/deploy/projects/httpbin/components/dev-httpbin
        uses: kustomize-set-image
      - config:
          outPath: ./out/dev-httpbin.gen.yaml
          path: ./src/deploy/projects/httpbin/components/dev-httpbin
        uses: kustomize-build
      - as: commit
        config:
          messageFromSteps:
          - update-image
          path: ./out
        uses: git-commit
      - config:
          path: ./out
          targetBranch: project/httpbin/component/dev-httpbin
        uses: git-push
      - config:
          apps:
          - name: httpbin-dev-httpbin
            sources:
            - desiredCommitFromStep: commit
              repoURL: https://github.com/jeffmccune/kargo-demo.git
        uses: argocd-update
  requestedFreight:
  - origin:
      kind: Warehouse
      name: httpbin
    sources:
      direct: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  labels:
    argocd.argoproj.io/instance: httpbin-kargo-stages
  name: prod-us-central
  namespace: httpbin
spec:
  promotionTemplate:
    spec:
      steps:
      - config:
          checkout:
          - branch: main
            path: ./src
          - branch: project/httpbin/component/prod-us-central-httpbin
            create: true
            path: ./out
          repoURL: https://github.com/jeffmccune/kargo-demo.git
        uses: git-clone
      - config:
          path: ./out
        uses: git-clear
      - as: update-image
        config:
          images:
          - image: quay.io/holos/mccutchen/go-httpbin
          path: ./src/deploy/projects/httpbin/components/prod-us-central-httpbin
        uses: kustomize-set-image
      - config:
          outPath: ./out/prod-us-central-httpbin.gen.yaml
          path: ./src/deploy/projects/httpbin/components/prod-us-central-httpbin
        uses: kustomize-build
      - as: commit
        config:
          messageFromSteps:
          - update-image
          path: ./out
        uses: git-commit
      - config:
          path: ./out
          targetBranch: project/httpbin/component/prod-us-central-httpbin
        uses: git-push
      - config:
          apps:
          - name: httpbin-prod-us-central-httpbin
            sources:
            - desiredCommitFromStep: commit
              repoURL: https://github.com/jeffmccune/kargo-demo.git
        uses: argocd-update
  requestedFreight:
  - origin:
      kind: Warehouse
      name: httpbin
    sources:
      stages:
      - uat
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  labels:
    argocd.argoproj.io/instance: httpbin-kargo-stages
  name: prod-us-east
  namespace: httpbin
spec:
  promotionTemplate:
    spec:
      steps:
      - config:
          checkout:
          - branch: main
            path: ./src
          - branch: project/httpbin/component/prod-us-east-httpbin
            create: true
            path: ./out
          repoURL: https://github.com/jeffmccune/kargo-demo.git
        uses: git-clone
      - config:
          path: ./out
        uses: git-clear
      - as: update-image
        config:
          images:
          - image: quay.io/holos/mccutchen/go-httpbin
          path: ./src/deploy/projects/httpbin/components/prod-us-east-httpbin
        uses: kustomize-set-image
      - config:
          outPath: ./out/prod-us-east-httpbin.gen.yaml
          path: ./src/deploy/projects/httpbin/components/prod-us-east-httpbin
        uses: kustomize-build
      - as: commit
        config:
          messageFromSteps:
          - update-image
          path: ./out
        uses: git-commit
      - config:
          path: ./out
          targetBranch: project/httpbin/component/prod-us-east-httpbin
        uses: git-push
      - config:
          apps:
          - name: httpbin-prod-us-east-httpbin
            sources:
            - desiredCommitFromStep: commit
              repoURL: https://github.com/jeffmccune/kargo-demo.git
        uses: argocd-update
  requestedFreight:
  - origin:
      kind: Warehouse
      name: httpbin
    sources:
      stages:
      - uat
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  labels:
    argocd.argoproj.io/instance: httpbin-kargo-stages
  name: prod-us-west
  namespace: httpbin
spec:
  promotionTemplate:
    spec:
      steps:
      - config:
          checkout:
          - branch: main
            path: ./src
          - branch: project/httpbin/component/prod-us-west-httpbin
            create: true
            path: ./out
          repoURL: https://github.com/jeffmccune/kargo-demo.git
        uses: git-clone
      - config:
          path: ./out
        uses: git-clear
      - as: update-image
        config:
          images:
          - image: quay.io/holos/mccutchen/go-httpbin
          path: ./src/deploy/projects/httpbin/components/prod-us-west-httpbin
        uses: kustomize-set-image
      - config:
          outPath: ./out/prod-us-west-httpbin.gen.yaml
          path: ./src/deploy/projects/httpbin/components/prod-us-west-httpbin
        uses: kustomize-build
      - as: commit
        config:
          messageFromSteps:
          - update-image
          path: ./out
        uses: git-commit
      - config:
          path: ./out
          targetBranch: project/httpbin/component/prod-us-west-httpbin
        uses: git-push
      - config:
          apps:
          - name: httpbin-prod-us-west-httpbin
            sources:
            - desiredCommitFromStep: commit
              repoURL: https://github.com/jeffmccune/kargo-demo.git
        uses: argocd-update
  requestedFreight:
  - origin:
      kind: Warehouse
      name: httpbin
    sources:
      stages:
      - uat
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  labels:
    argocd.argoproj.io/instance: httpbin-kargo-stages
  name: test
  namespace: httpbin
spec:
  promotionTemplate:
    spec:
      steps:
      - config:
          checkout:
          - branch: main
            path: ./src
          - branch: project/httpbin/component/test-httpbin
            create: true
            path: ./out
          repoURL: https://github.com/jeffmccune/kargo-demo.git
        uses: git-clone
      - config:
          path: ./out
        uses: git-clear
      - as: update-image
        config:
          images:
          - image: quay.io/holos/mccutchen/go-httpbin
          path: ./src/deploy/projects/httpbin/components/test-httpbin
        uses: kustomize-set-image
      - config:
          outPath: ./out/test-httpbin.gen.yaml
          path: ./src/deploy/projects/httpbin/components/test-httpbin
        uses: kustomize-build
      - as: commit
        config:
          messageFromSteps:
          - update-image
          path: ./out
        uses: git-commit
      - config:
          path: ./out
          targetBranch: project/httpbin/component/test-httpbin
        uses: git-push
      - config:
          apps:
          - name: httpbin-test-httpbin
            sources:
            - desiredCommitFromStep: commit
              repoURL: https://github.com/jeffmccune/kargo-demo.git
        uses: argocd-update
  requestedFreight:
  - origin:
      kind: Warehouse
      name: httpbin
    sources:
      stages:
      - dev
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  labels:
    argocd.argoproj.io/instance: httpbin-kargo-stages
  name: uat
  namespace: httpbin
spec:
  promotionTemplate:
    spec:
      steps:
      - config:
          checkout:
          - branch: main
            path: ./src
          - branch: project/httpbin/component/uat-httpbin
            create: true
            path: ./out
          repoURL: https://github.com/jeffmccune/kargo-demo.git
        uses: git-clone
      - config:
          path: ./out
        uses: git-clear
      - as: update-image
        config:
          images:
          - image: quay.io/holos/mccutchen/go-httpbin
          path: ./src/deploy/projects/httpbin/components/uat-httpbin
        uses: kustomize-set-image
      - config:
          outPath: ./out/uat-httpbin.gen.yaml
          path: ./src/deploy/projects/httpbin/components/uat-httpbin
        uses: kustomize-build
      - as: commit
        config:
          messageFromSteps:
          - update-image
          path: ./out
        uses: git-commit
      - config:
          path: ./out
          targetBranch: project/httpbin/component/uat-httpbin
        uses: git-push
      - config:
          apps:
          - name: httpbin-uat-httpbin
            sources:
            - desiredCommitFromStep: commit
              repoURL: https://github.com/jeffmccune/kargo-demo.git
        uses: argocd-update
  requestedFreight:
  - origin:
      kind: Warehouse
      name: httpbin
    sources:
      stages:
      - test
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  labels:
    argocd.argoproj.io/instance: httpbin-kargo-stages
  name: httpbin
  namespace: httpbin
spec:
  interval: 5m0s
  subscriptions:
  - image:
      discoveryLimit: 5
      repoURL: quay.io/holos/mccutchen/go-httpbin
      semverConstraint: ^2.0.0
      strictSemvers: true
