apiVersion: v1
kind: Service
metadata:
  labels:
    argocd.argoproj.io/instance: httpbin-test-httpbin
  name: httpbin
  namespace: test-httpbin
spec:
  ports:
  - appProtocol: http
    name: http
    port: 80
    protocol: TCP
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    argocd.argoproj.io/instance: httpbin-test-httpbin
  name: httpbin
  namespace: test-httpbin
spec:
  template:
    spec:
      containers:
      - image: quay.io/holos/mccutchen/go-httpbin:v2.15.0
        livenessProbe:
          httpGet:
            path: /status/200
            port: http
        name: httpbin
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /status/200
            port: http
        resources: {}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  labels:
    argocd.argoproj.io/instance: httpbin-test-httpbin
  name: istio-ingress
  namespace: test-httpbin
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: istio-ingress
  to:
  - group: ""
    kind: Service
