apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  annotations:
    link.argocd.argoproj.io/external-link: https://kargo.holos.localhost/project/external-secrets
  labels:
    argocd.argoproj.io/instance: security-external-secrets-promoter
  name: external-secrets
spec:
  promotionPolicies:
  - autoPromotionEnabled: true
    stage: main
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  annotations:
    link.argocd.argoproj.io/external-link: https://kargo.holos.localhost/project/external-secrets/stage/main
  labels:
    argocd.argoproj.io/instance: security-external-secrets-promoter
  name: main
  namespace: external-secrets
spec:
  promotionTemplate:
    spec:
      steps:
      - config:
          checkout:
          - branch: main
            path: ./src
          repoURL: https://github.com/jeffmccune/kargo-demo.git
        uses: git-clone
      - as: update
        config:
          path: src/config/externalsecrets/externalsecrets.yaml
          updates:
          - key: chart.version
            value: ${{ chartFrom('https://charts.external-secrets.io', 'external-secrets',
              warehouse('external-secrets')).Version }}
        uses: yaml-update
      - as: commit
        config:
          message: 'external-secrets: update to ${{ chartFrom(''https://charts.external-secrets.io'',
            ''external-secrets'', warehouse(''external-secrets'')).Version }}'
          path: ./src
        uses: git-commit
      - as: push
        config:
          generateTargetBranch: true
          path: ./src
        uses: git-push
      - as: pull
        config:
          repoURL: https://github.com/jeffmccune/kargo-demo.git
          sourceBranch: ${{ outputs.push.branch }}
          targetBranch: main
        uses: git-open-pr
  requestedFreight:
  - origin:
      kind: Warehouse
      name: external-secrets
    sources:
      direct: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  annotations:
    link.argocd.argoproj.io/external-link: https://kargo.holos.localhost/project/external-secrets/warehouse/external-secrets
  labels:
    argocd.argoproj.io/instance: security-external-secrets-promoter
  name: external-secrets
  namespace: external-secrets
spec:
  freightCreationPolicy: Automatic
  interval: 5m0s
  subscriptions:
  - chart:
      name: external-secrets
      repoURL: https://charts.external-secrets.io
