apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  annotations:
    link.argocd.argoproj.io/external-link: https://kargo.holos.localhost/project/cert-manager
  labels:
    argocd.argoproj.io/instance: security-cert-manager-promoter
  name: cert-manager
spec:
  promotionPolicies:
  - autoPromotionEnabled: true
    stage: main
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  annotations:
    link.argocd.argoproj.io/external-link: https://kargo.holos.localhost/project/cert-manager/stage/main
  labels:
    argocd.argoproj.io/instance: security-cert-manager-promoter
  name: main
  namespace: cert-manager
spec:
  promotionTemplate:
    spec:
      steps:
      - config:
          checkout:
          - branch: main
            path: ./src
          repoURL: https://github.com/holos-run/kargo-demo.git
        uses: git-clone
      - as: update
        config:
          path: src/config/certmanager/cert-manager.yaml
          updates:
          - key: chart.version
            value: ${{ chartFrom('https://charts.jetstack.io', 'cert-manager', warehouse('cert-manager')).Version
              }}
        uses: yaml-update
      - as: commit
        config:
          message: 'cert-manager: update to ${{ chartFrom(''https://charts.jetstack.io'',
            ''cert-manager'', warehouse(''cert-manager'')).Version }}'
          path: ./src
        uses: git-commit
      - as: push
        config:
          generateTargetBranch: true
          path: ./src
        uses: git-push
      - as: pull
        config:
          repoURL: https://github.com/holos-run/kargo-demo.git
          sourceBranch: ${{ outputs.push.branch }}
          targetBranch: main
        uses: git-open-pr
  requestedFreight:
  - origin:
      kind: Warehouse
      name: cert-manager
    sources:
      direct: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  annotations:
    link.argocd.argoproj.io/external-link: https://kargo.holos.localhost/project/cert-manager/warehouse/cert-manager
  labels:
    argocd.argoproj.io/instance: security-cert-manager-promoter
  name: cert-manager
  namespace: cert-manager
spec:
  freightCreationPolicy: Automatic
  interval: 5m0s
  subscriptions:
  - chart:
      name: cert-manager
      repoURL: https://charts.jetstack.io
