apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    annotations:
        kargo.akuity.io/authorized-stage: podinfo:dev
    labels:
        stage: dev
        tier: nonprod
    name: podinfo-dev-podinfo
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: podinfo
    source:
        path: ./
        repoURL: https://github.com/jeffmccune/kargo-demo.git
        targetRevision: project/podinfo/component/dev-podinfo
