apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    labels: {}
    name: podinfo-kargo-project
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: podinfo
    source:
        path: deploy/projects/podinfo/components/kargo-project
        repoURL: https://github.com/jeffmccune/kargo-demo.git
        targetRevision: main
