apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    annotations:
        kargo.akuity.io/authorized-stage: podinfo:prod-us-west
    labels:
        stage: prod-us-west
        tier: prod
    name: podinfo-prod-us-west-podinfo
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: podinfo
    source:
        path: ./
        repoURL: https://github.com/jeffmccune/kargo-demo.git
        targetRevision: project/podinfo/component/prod-us-west-podinfo
