#! /bin/bash

# cd to the repository root
TOPLEVEL="$(cd $(dirname "$0") && cd .. && pwd)"
cd "$TOPLEVEL"

set -xeuo pipefail

# We want to test against the same code users are using as a reference.
export HOLOS_WORKDIR_ROOT="${TOPLEVEL}"

go test
