apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  labels:
    argocd.argoproj.io/instance: security-cert-manager-kargo
  name: cert-manager
spec:
  promotionPolicies:
  - stage: main
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  labels:
    argocd.argoproj.io/instance: security-cert-manager-kargo
  name: cert-manager
  namespace: cert-manager
spec:
  freightCreationPolicy: Automatic
  interval: 5m0s
  subscriptions:
  - chart:
      name: cert-manager
      repoURL: https://charts.jetstack.io
