apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    labels: {}
    name: network-httproutes
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: network
    source:
        path: deploy/components/httproutes
        repoURL: https://github.com/jeffmccune/kargo-demo.git
        targetRevision: main
